ci(windows): add mirrored/retried gmp download fallback

diff --git a/.github/workflows/windows_ci.yml b/.github/workflows/windows_ci.yml
--- a/.github/workflows/windows_ci.yml
+++ b/.github/workflows/windows_ci.yml
@@ -28,6 +28,7 @@ jobs:
           automake,
           cmake,
           coreutils,
+          curl,
           gperf,
           libtool,
           m4,
@@ -41,16 +42,44 @@ jobs:
       shell: bash
       env:
         CYGWIN: winsymlinks:native
-      run: >-
-        pushd . && 
-        mkdir -p /tools && cd /tools && mkdir -p dynamic_gmp && mkdir -p static_gmp && 
-        wget https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz &&
-        tar xf gmp-6.3.0.tar.xz && 
-        cd gmp-6.3.0 &&
-        ./configure --host=x86_64-w64-mingw32 --build=i686-pc-cygwin --enable-cxx --enable-shared --disable-static --prefix=/tools/dynamic_gmp &&
-        make && make install && make clean && 
-        ./configure --host=x86_64-w64-mingw32 --build=i686-pc-cygwin --enable-cxx --enable-static --disable-shared --prefix=/tools/static_gmp && 
-        make && make install && 
+      run: |
+        pushd .
+        mkdir -p /tools
+        cd /tools
+        mkdir -p dynamic_gmp static_gmp
+
+        gmp_archive=gmp-6.3.0.tar.xz
+        download_ok=0
+        for url in \
+          https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz \
+          https://mirrors.kernel.org/gnu/gmp/gmp-6.3.0.tar.xz \
+          https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz
+        do
+          echo "Trying $url"
+          if curl -fL --retry 5 --retry-delay 2 --connect-timeout 20 --max-time 600 "$url" -o "$gmp_archive"; then
+            download_ok=1
+            break
+          fi
+          if wget --tries=5 --timeout=20 -O "$gmp_archive" "$url"; then
+            download_ok=1
+            break
+          fi
+        done
+
+        if [ "$download_ok" -ne 1 ]; then
+          echo "Failed to download $gmp_archive from all mirrors"
+          exit 1
+        fi
+
+        tar xf "$gmp_archive"
+        cd gmp-6.3.0
+        ./configure --host=x86_64-w64-mingw32 --build=i686-pc-cygwin --enable-cxx --enable-shared --disable-static --prefix=/tools/dynamic_gmp
+        make
+        make install
+        make clean
+        ./configure --host=x86_64-w64-mingw32 --build=i686-pc-cygwin --enable-cxx --enable-static --disable-shared --prefix=/tools/static_gmp
+        make
+        make install
         popd
 
     - name: Building MCSAT Dependencies
